nome= input("insira o nome do funcionario: ")
salario= float(input("salario base: "))
salarioatual= float(input("salario atual: "))
total= float(salario) + float(salarioatual*0.25)
print = ("seu salario é R$%.2f" %(Nome, total))
